changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} ({{.Time.Format "January 2, 2006"}})'
kindFormat: '{{.Kind}}:'
changeFormat: '* {{.Body}}'
kinds:
- label: FEATURES
  auto: minor
- label: BUG FIXES
  auto: minor
- label: ENHANCEMENTS
  auto: minor
- label: WARNING
newlines:
  beforeKind: 1
  endOfVersion: 4
envPrefix: CHANGIE_
